# Generated by Django 3.0.2 on 2020-02-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(default='', max_length=200)),
                ('keyPhrase', models.TextField()),
                ('num', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'title',
                'verbose_name_plural': 'title',
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='totalKeyPhrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('frequency', models.FloatField(default=0.0)),
                ('titles', models.TextField()),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': 'content',
                'ordering': ['frequency'],
            },
        ),
    ]
